kind = "web"
previewPath = "/"
title = "Рабочая среда"
version = "1.0.0"
id = "artifacts/kot"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25118

[services.development]
run = "pnpm --filter @workspace/kot run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kot", "run", "build" ]
publicDir = "artifacts/kot/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25118"
BASE_PATH = "/"
